OBJS = 06_extension_libraries_and_loading_other_image_formats.c

CC = gcc

COMPILER_FLAGS = -Wall -Wextra -pedantic

LINKER_FLAGS = -lSDL2 -lSDL2_image

OBJ_NAME = p06_extension_libraries_and_loading_other_image_formats

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
